server.port=${PORT:8080}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dawygcqzs}
cloudinary.api_key=${CLOUDINARY_API_KEY:463654647176597}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:oxPjujAxD8wuIGdpxkXcHzzX-Is}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB
server.tomcat.max-http-form-post-size=30MB

app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:8080,http://localhost:8081,https://picselkdkce021.netlify.app,http://localhost:5173}
